### ISSUE TITLE
displaying html code and other code in posts

### ISSUE THREAD

**Issue by ppdcom** [bruninoit/hashtag#1]
Hi,

I have just tested this module with 3.1.3 and there is serious bug that its output the html code in posts and conflict with other plugins as well. when I use this its output code like this 

http://pastebin.com/65U1r49y

**Comment by bruninoit** [comment]
Thanks.... I know it... I'll resolve it as soon as possible.

**Comment by Galixte** [comment]
Hi @bruninoit,

any news about that ?

**Comment by bruninoit** [comment]
I've abbandoned definitively this ext.

**Comment by Galixte** [comment]
Maybe it can be closed.
